apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: backend-service-trigger-template
  namespace: devops
spec:
  params:
    - name: BRANCH
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: backend-service-pipeline-run-
        namespace: devops
      spec:
        pipelineRef:
          name: backend-service-pipeline
        taskRunTemplate:
          serviceAccountName: pipeline
        timeouts:
          pipeline: 1h0m0s
        params:
          - name: BRANCH
            value: $(tt.params.BRANCH)
        workspaces:
          - name: pipeline-backend-service-workspace
            volumeClaimTemplate:
              metadata:
                creationTimestamp: null
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: ibm-spectrum-scale-sample
                volumeMode: Filesystem
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: backend-service-trigger-binding
  namespace: devops
spec:
  params:
    - name: BRANCH
      value: $(body.branch)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: backend-service-webhook
  namespace: devops
spec:
  serviceAccountName: pipeline
  triggers:
    - name: backend-service-trigger
      bindings:
        - ref: backend-service-trigger-binding
      template:
        ref: backend-service-trigger-template
